config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  resources :categories
  devise_for :users
  devise_scope :user do
    authenticated :user do
    root :to => 'categories#new', as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_filter :authenticate_user!  
  def new
        @category = Category.new
  end

  def index
        @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
       if @category.save
        flash[:notice] = "Category Saved Successfully"
        redirect_to :controller => "products", :action => "new"
       else
        flash[:notice] = "Error"
        render "new"
       end
  end

  def edit
        @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attribute(category_params)
      flash[:notice] = "Category Updated Successfully"
      redirect_to :controller => "categories", :action => "index"
    else
      render "edit"
    end
  end


private
  def category_params
    params.require(:category).permit(:name,:about)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_filter :authenticate_user!
require 'will_paginate/array'

  def new
  	@product = Product.new
  end

  def index
  	#@products = Product.all
  	#@products = Product.all.paginate("created_at ASC" ,:page => params[:page], :per_page => 2)
  	#@products = Product.order(:name).page(params[:page]).per(2)
    @products = Product.order("created_at desc").page(params[:page]).per_page(2)


  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @products }
    format.js
  end
  end

  def create
		@product = Product.new(product_params)
       if @product.save
       	flash[:notice] = "product Saved Successfully"
       	redirect_to :controller => "products", :action => "index"
       else
       	flash[:notice] = "Error"
       	render "new"
       end
	end

  def edit
  	@product = Product.find(params[:id])
  end

  def show
  	@product = Product.find(params[:id])
  end

  private
	def product_params
		params.require(:product).permit(:user_id,:category_id,:name,:cost)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<div class="jumbotron text-center">
<h1 align="center">New Categories</h1>
</div>

<div class="container">
 <%= form_for @category do |c| %>
	
	<div class="form-group">
  	<%= c.label :name %>
  </div>
  <div class="form-group">
  	<%= c.text_field :name, :required => true %> </br>
	</div>

	<div class="form-group">
		<%= c.label :about %>
	</div>
  <div class="form-group">
		<%= c.text_area :about, :required => true %>
	</div>

  <div class="action">
  	<%= c.submit "Save Category"%>
  </div>
  
  <%end%>
</div>

<style type="text/css">
  body
  {
    background-color: #ce14b8;
  }
  .form-group
  {
    margin-left: 650px;
    padding: -10px;
    margin-top: 60px;
  }
  .action
  {
    margin-left: 680px;
    margin-top: 20px;
  }
</style>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div class="table">

 <table>
 	<thead>
 		<tr>
		 	<th>Name</th>
		 	<th>About</th>
 		</tr>
 	</thead>
 <tbody>
 <% @categories.each do |c| %>
 	<tr>
	 	<td><%= c.name %></td>
	 	<td><%= c.about %></td>
 	</tr>
 <%end%>
 </tbody>
</table>
</div>
<br />

<% if user_signed_in? %>
	<%= current_user.email %><br />
	<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% end %>

<style type="text/css">
	body
	{
		background-color: #ce14b8;
	}
</style>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientProduct</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="jumbotron text-center">
<h1 align="center">New Projects</h1>
</div>

<div class="container">
 <%= form_for Product.new do |c| %>
	
  <div class="label-field">
  	<%= c.label :user_id %>
  </div>

  <div class="text-field">
  	<%#= c.collection_select(:product, :user_id, User.all, :id, :email)%>
  	<%#= c.select :user_id, User.all.collect {|x| [x.email, x.id]}, :prompt => "Please Select" %>
    <%= c.select :user_id, User.order("email ASC").map { |p| [p.email, p.id]}, :prompt => "Please Select User" %>

  </div>

  <div class="label-field">
  	<%= c.label :category_id %>
  </div>

  <div class="text-field">
  <%= c.select :category_id, Category.order("name ASC").map {|x| [x.name, x.id]}, :prompt => "Please Select"%>
  <%#= c.select :user_id, User.order("email ASC").map { |p| [p.email, p.id]}, :prompt => "Please Select User" %>

  	<%#= c.collection_select(:product, :cat_id, Category.all, :id, :name)%>
  </div>

  <div class="label-field">
  	<%= c.label :name %>
  </div>
  <div class="text-field">
  	<%= c.text_field :name, :required => true %> </br>
	</div>

	<div class="label-field">
		<%= c.label :cost %>
	</div>
  <div class="text-field">
		<%= c.text_field :cost, :required => true %>
	</div>

  <div class="action">
  	<%= c.submit "Save Products"%>
  </div>
  
  <%end%>
</div>

<style type="text/css">
  body
  {
    background-color: #ce14b8; 
  }
  .container
  {
    width: 600px;
    text-align: center;
    margin-left: 300px;
  }
  .text-field
  {
    margin-top: 0px;
    width: 1000px;
  }
  .label-field
  {
    padding: 20px;
    width: 500px;
  }
</style>

app/views/products/_products.html.erb
<table class="table">
	<thead>
		<tr>
		   <th>SI No</th>
			<th>Projects</th>
			<th>Username</th>
			<th>Category Name</th>
		</tr>
	</thead>
	<%count = 0%>
	<tbody>
	<% @products.each do |p|%>
		<tr>
		    <td><%= count += 1%></td>
			<td><%= p.name%></td>
			<td><%= p.user.email%></td>
			<td><%= p.category.name%></td>
		</tr>
	</tbody>
	<%end%>
</table>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @products, :container => false %>
  </div>


<br />
<% if user_signed_in? %>
	<b> User:</b><%= current_user.email %>
	<b><%= link_to 'Log out', destroy_user_session_path, method: :delete %></b>
<%end%>

app/views/products/edit.html.erb
<%= render "form" %>

app/views/products/index.html.erb
<h1>Products</h1>
<div id="products">
    <%= render "products/products" %>
</div>
<script>
$(function(){
   $('.pagination a').attr('data-remote', 'true')
});
</script>
<div class="new-product">
	<%= link_to "Create Product", :controller => "products", :action => "new"%><br />
	<%= link_to "Back", :controller => "products", :action => "index"%>
</div>

<style type="text/css">
	body
	{
		background-color: #ce14b8;
	}
</style>

app/views/products/index.js.erb
jQuery('#products').html(" 'products/products' )%>");
$('.pagination a').attr('data-remote', 'true');

app/views/products/new.html.erb
<%= render "form" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>